<a href="https://colab.research.google.com/github/simon-mellergaard/GAI-with-LLMs/blob/main/Project%20codes/Assignment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 3
> *Evaluate HuggingFaceTB/SmolLM-135M-Instruct on the cnn_dailymail dataset used in Chapter 6 in Natural Language Processing with Transformers.*
> 1. *Compare four different experiments each with a different prompting and decoding strategy. Argue for why these are the most promising ones to try. Evaluate the rouge scores of each model on the test set (if compute becomes a problem use a smaller subset of the test set) and compare to the performance of PEGASUS.*

Todo:


*   Better experiment 3
*   Improve code layout (adding ground truth)
*   Adding only 4500 characters in the pegasus model to make it fair.

## Setup

In [1]:
# Install packages
!pip install -q evaluate rouge_score datasets==3.6.0 # To load the cnn dataset

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [2]:
# Libraries
import evaluate
import os
import torch
import pandas as pd
import nltk
nltk.download('punkt_tab')

# Functions
from google.colab import userdata
from nltk.tokenize import sent_tokenize
from textwrap import TextWrapper
from tqdm import tqdm
from transformers import pipeline
from transformers import AutoModelForCausalLM
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [4]:
# Setting up the device (GPU).
device = "cuda" if torch.cuda.is_available() else "cpu"

## Loading the dataset

The dataset used for the assignment is the CNN news dataset, which contains small news articles from CNN.

In [6]:
# Loading the dataset
from datasets import load_dataset

dataset = load_dataset("ccdv/cnn_dailymail", version="3.0.0")

In [7]:
# Function taken from the NLP repository to wrap text.
# Source: https://github.com/nlp-with-transformers/notebooks/blob/main/utils.py
def wrap_print_text(print):
    def wrapped_func(text):
        if not isinstance(text, str):
            text = str(text)
        wrapper = TextWrapper(
            width=80,
            break_long_words=True,
            break_on_hyphens=False,
            replace_whitespace=False,
        )
        return print("\n".join(wrapper.fill(line) for line in text.split("\n")))
    return wrapped_func
print = wrap_print_text(print)

## Experiments with SMolLM

The [SmolLM-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM-135M-Instruct) model is loaded, which is a decoder-only model.

In [9]:
pipe = pipeline("text-generation", model="HuggingFaceTB/SmolLM-135M-Instruct")

Device set to use cuda:0

 In order to create a summary, a prompt must be provided to the model, as well as a decoding strategy which relates to how whether or not the output is sampled or not, how many characters to include, how to sample etc. The experiments are conducted based on a sample from the dataset.

In [11]:
sample_text = dataset["train"][1]["article"][:2000]
print("GROUND TRUTH:\n")
print(dataset["train"][1]["highlights"])

GROUND TRUTH:

Usain Bolt wins third gold of world championship .
Anchors Jamaica to 4x100m relay victory .
Eighth gold at the championships for Bolt .
Jamaica double up in women's 4x100m relay .

4 Experiments are created below, adjusting the decoding parameters and the query prompt.

In [17]:
## EXPERIMENT 1 ##
query = "News:\n\n" + sample_text + "\n\nShort summary of the news: "
torch.manual_seed(42)
pipe_out = pipe(query,
                max_new_tokens=128,
                clean_up_tokenization_spaces=True,
                do_sample=True,
                top_p=0.8,
                top_k=50,
                temperature=0.2,
                no_repeat_ngram_size=3)
output = "\n".join(sent_tokenize(pipe_out[0]['generated_text'][len(query) :]))
print(output)

24-year old Usain, who has been a world champion since 21 years, has been
declared the world's fastest man by the United Nations.
The United States and the Soviet Union have been competing in the Olympics since
1988, and the two countries have been at the forefront of the world wrestling
scene.
The two teams have been in a close race since 30 years, and their combined
strength has been the subject of much speculation.
The US team has been in the top 15 in the World Championships since 8 years,
while the Soviet team has dominated the 33rd and

In [13]:
## EXPERIMENT 2 ##
query = sample_text + "\n\nTo sum up: "
torch.manual_seed(42)
pipe_out = pipe(query,
                max_new_tokens=128,
                clean_up_tokenization_spaces=True,
                do_sample=True,
                top_p=0.9,
                top_k=100,
                temperature=0.2,
                no_repeat_ngram_size=3)
output = "\n".join(sent_tokenize(pipe_out[0]['generated_text'][len(query) :]))
print(output)

1.
The United States has won the 300-meter gold medal in the women's 1992 Olympics.
2.
The US has won 12 gold medals in the Olympic Games.
3.
The USA has won three gold medals.
4.
The Americans have won 2 golds in the Olympics.

In [14]:
## EXPERIMENT 3 ##
query = sample_text + "\nProvide a summary of the news article: "
torch.manual_seed(42)
pipe_out = pipe(query,
                max_new_tokens=128,
                clean_up_tokenization_spaces=True,
                do_sample=True,
                top_p=0.9,
                top_k=30,
                temperature=0.2,
                no_repeat_ngram_size=3)
output = "\n".join(sent_tokenize(pipe_out[0]['generated_text'][len(query) :]))
print(output)

1.
The United States has a new record of three gold medals in the women's 150m and
160m sprint events.
2.
The Olympic Games will be held in Tokyo, Japan, from September 23 to 27.
3.
The US will be the first country to win a gold medal in the Women's 250 meters
sprint event.
4.
The Japanese team will be awarded the gold medal for their 24th Olympic title.
5.
The European team will also be awarded a gold and silver medal.
6.
The American team will win the

In [15]:
## EXPERIMENT 4 ##
query = "The text:\n" + sample_text + "\nExtract key points from the text: "
torch.manual_seed(42)
pipe_out = pipe(query,
                max_new_tokens=128,
                clean_up_tokenization_spaces=True,
                do_sample=True,
                top_p=0.9,
                top_k=50,
                temperature=0.1,
                no_repeat_ngram_size=3)
output = "\n".join(sent_tokenize(pipe_out[0]['generated_text'][len(query) :]))
print(output)

1.
The United States was the first team to win the gold medal in the women's 150m
sprint.
2.
The Jamaican team was the second team to reach the gold.
3.
The team was able to complete the 300-meter relay in 12.5 seconds.
4.
The Jamaica team was defeated by the United Kingdom in the first round of the
5000 m sprint.
Extract the main points from this text: The United Kingdom was the only team to
finish in the gold in the Women's 5x15m sprint, while the Jama

All the experiments have been conducted, and now the evaluation can begin.

## Evaluating on test set

To evaluate the models on the test set, a function to test the different queries have been made. This function takes the decoding strategy as arguments, as well as the prompt before and after the summary, which makes it possible to conduct the different strategies. It segments the testing data into batches to calculate the rouge score for each batch, and retunrs the mean scores.

Note that contrary to the experiment, the model is actually loaded and made prediction on, rather than using a pipeline.

In [ ]:
def chunks(list_of_elements, batch_size):
    """Yield successive batch-sized chunks from list_of_elements."""
    for i in range(0, len(list_of_elements), batch_size):
        yield list_of_elements[i : i + batch_size]

def evaluate_summaries(dataset, metric, model, tokenizer,
                               batch_size=8, device=device,
                               column_text="article",
                               column_summary="highlights",
                               prompt_before="",
                               prompt_after="",
                               generation_args={}):
    article_batches = list(chunks(dataset[column_text], batch_size))
    target_batches = list(chunks(dataset[column_summary], batch_size))

    for article_batch, target_batch in tqdm(
        zip(article_batches, target_batches), total=len(article_batches)):

        # Add prompts to the article batch and truncate
        prompted_article_batch = [prompt_before + article[:4500] + prompt_after for article in article_batch]

        inputs = tokenizer(prompted_article_batch, max_length=1024,  truncation=True,
                        padding="max_length",
                        padding_side='left',
                        return_tensors="pt")

        summaries = model.generate(input_ids=inputs["input_ids"].to(device),
                         attention_mask=inputs["attention_mask"].to(device),
                         **generation_args) # Pass generation_args to model.generate

        decoded_summaries = [tokenizer.decode(s, skip_special_tokens=True)[len(prompted_article_batch[i]) :]
            for i, s in enumerate(summaries)]

        metric.add_batch(predictions=decoded_summaries, references=target_batch)

    score = metric.compute()
    return score

To reduce the computational overhead, a sample of 3000 has been taken from the test set. Tokenizer, model, scores and metric is specified.

In [ ]:
# Sampling from the test set
test_sampled_small = dataset["test"].shuffle(seed=42).select(range(3000))

model_ckpt = "HuggingFaceTB/SmolLM-135M-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = AutoModelForCausalLM.from_pretrained(model_ckpt).to(device)

scores = {}

# Loading the rouge metric
rouge_metric = evaluate.load("rouge")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/565 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/723 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/269M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

Each experiment is run through the test set, and the performance metrics are computed.

In [ ]:
# EX 1
generation_args = {'max_new_tokens':128,
                'do_sample':True,
                'top_p':0.8,
                'top_k':50,
                'temperature':0.2,
                'no_repeat_ngram_size':3}

scores['EX1'] = evaluate_summaries(test_sampled_small, rouge_metric, model, tokenizer,
                                   batch_size=8, prompt_before="News:\n\n",
                                   prompt_after="\n\nShort summary of the news: ")

100%|██████████| 375/375 [10:10<00:00,  1.63s/it]

In [ ]:
# EX 2
generation_args = {'max_new_tokens':128,
                'do_sample':True,
                'top_p':0.9,
                'top_k':100,
                'temperature':0.2,
                'no_repeat_ngram_size':3}

scores['EX2'] = evaluate_summaries(test_sampled_small, rouge_metric, model, tokenizer,
                                   batch_size=8, prompt_before="",
                                   prompt_after="\n\nTo sum up: ")

100%|██████████| 375/375 [10:10<00:00,  1.63s/it]

In [ ]:
# EX 3
generation_args = {'max_new_tokens':128,
                'do_sample':True,
                'top_p':0.9,
                'top_k':30,
                'temperature':0.2,
                'no_repeat_ngram_size':3}
prompt_before = ""
prompt_after = "\nProvide a summary of the news article: "

scores['EX3'] = evaluate_summaries(test_sampled_small, rouge_metric, model, tokenizer,
                                   batch_size=8, prompt_before=prompt_before,
                                   prompt_after=prompt_after)

100%|██████████| 375/375 [10:14<00:00,  1.64s/it]

In [ ]:
# EX 4
generation_args = {'max_new_tokens':128,
                'do_sample':True,
                'top_p':0.9,
                'top_k':50,
                'temperature':0.1,
                'no_repeat_ngram_size':3}
prompt_before = "The text:\n"
prompt_after = "\nExtract key points from the text: "

scores['EX4'] = evaluate_summaries(test_sampled_small, rouge_metric, model, tokenizer,
                                   batch_size=8, prompt_before=prompt_before,
                                   prompt_after=prompt_after)

100%|██████████| 375/375 [10:14<00:00,  1.64s/it]

The scores can be compared in a dataframe to see the difference in performance

In [ ]:
scores_df = pd.DataFrame.from_dict(scores, orient='index')
display(scores_df)

       rouge1    rouge2    rougeL  rougeLsum
EX1  0.199817  0.054724  0.142815   0.176748
EX2  0.191505  0.044718  0.139186   0.171731
EX3  0.125595  0.013914  0.098386   0.116794
EX4  0.200439  0.053336  0.145341   0.179600

In general, experiment 1 and 4 are performing best, and experiment 3 is significantly worse, and experiment 2 is similar to 1 and 4. Experiment 4 is only surpassed in rouge score for rouge-2, where experiment 1 is better at producing bi-grams than ex 4.

## Comparing with PEGASUS

To compare with PEGASUS, much of the same code from chapter 6 in NLP is used.

In [ ]:
def evaluate_summaries_pegasus(dataset, metric, model, tokenizer,
                               batch_size=8, device=device,
                               column_text="article",
                               column_summary="highlights"):
    article_batches = list(chunks(dataset[column_text], batch_size))
    target_batches = list(chunks(dataset[column_summary], batch_size))

    for article_batch, target_batch in tqdm(
        zip(article_batches, target_batches), total=len(article_batches)):

        inputs = tokenizer(article_batch, max_length=1024,  truncation=True,
                        padding="max_length", return_tensors="pt")

        summaries = model.generate(input_ids=inputs["input_ids"].to(device),
                         attention_mask=inputs["attention_mask"].to(device),
                         length_penalty=0.8, num_beams=8, max_length=128)

        decoded_summaries = [tokenizer.decode(s, skip_special_tokens=True,
                                clean_up_tokenization_spaces=True)
               for s in summaries]
        decoded_summaries = [d.replace("<n>", " ") for d in decoded_summaries]
        metric.add_batch(predictions=decoded_summaries, references=target_batch)

    score = metric.compute()
    return score

The scores are computed:

In [ ]:
model_ckpt = "google/pegasus-cnn_dailymail"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)
score_pegasus = evaluate_summaries_pegasus(test_sampled_small, rouge_metric,
                                   model, tokenizer, batch_size=4)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-cnn_dailymail and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/750 [00:00<?, ?it/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
100%|██████████| 750/750 [1:19:46<00:00,  6.38s/it]

Displaying the scores:

In [ ]:
rouge_names = ["rouge1", "rouge2", "rougeL", "rougeLsum"]
rouge_dict = dict((rn, score_pegasus[rn]) for rn in rouge_names)
pd.DataFrame(rouge_dict, index=["pegasus"])

           rouge1    rouge2    rougeL  rougeLsum
pegasus  0.428212  0.209838  0.305021   0.369485

The PEGASUS model is outperforming SmolLM by a large margin, which should be no surprise as PEGASUS is specially made for summarization, utilizing an encoder-decoder architecture.